nodeLinker: node-modules

packageExtensions:
  "cmdk@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "react-day-picker@*":
    peerDependencies:
      date-fns: "*"
  "embla-carousel-autoplay@*":
    peerDependencies:
      embla-carousel: "*"
  "recharts@*":
    peerDependencies:
      react-is: "*"